name: Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish EXE
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./publish

    - name: Copy and Convert PS1 script
      run: |
        $src = "./Win11FixExpRightClick.ps1"
        $dest = "./publish/Win11FixExpRightClick.ps1"
        (Get-Content $src) | Set-Content -Path $dest -Encoding UTF8BOM

    - name: Copy Run.bat
      run: Copy-Item "./Run.bat" -Destination "./publish/"

    - name: Get Short SHA
      id: vars
      run: echo "sha_short=$($env:GITHUB_SHA.Substring(0, 7))" >> $env:GITHUB_OUTPUT

    - name: Compress EXE to ZIP
      run: |
        $productName = "Win11FixExpRightClick"
        $tag = "${{ steps.vars.outputs.sha_short }}"
        $zipName = "EXE-$productName`_$tag.zip"
        7z a -tzip -mx=9 "./publish/$zipName" "./publish/$productName.exe"

    - name: Compress PS1 to ZIP
      run: |
        $productName = "Win11FixExpRightClick"
        $tag = "${{ steps.vars.outputs.sha_short }}"
        $zipName = "PS1-$productName`_$tag.zip"

        7z a -tzip -mx=9 "./publish/$zipName" "./publish/$productName.ps1" "./publish/Run.bat"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.sha_short }}
        name: Release ${{ steps.vars.outputs.sha_short }}
        files: |
          ./publish/EXE-*.zip
          ./publish/PS1-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
